services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: trego_pack
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d trego_pack"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backpack.wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
volumes:
  postgres_data: