# Generated by Django 4.2.21 on 2025-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trego', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
